[package]
name = "faust_benchmarks"
version = "0.1.0"
authors = ["Fabian Keller <github.100.fkeller@spamgourmet.com>"]
edition = "2018"

[dependencies]

libm = "*"
hound = "3.4.0"

num-traits = "0.2"

portaudio = "*"
rand = "*"
